---
title: "STA 640 Final Project"
author: "Joon Sup Park, Jaskaran Singh"
date: '2022/04/17'
output: pdf_document
---

```{r setup, message=F, warning=F, echo=F}
library(tidyverse)
library(dplyr)
library(ggplot2)
library(glm2)
library(PSweight)
library(mvtnorm)
library(rje)
library(reshape2)
library(gridExtra)
```

```{r}
#set.seed(1652)

generate_data <- function(n,p){
  W_mean = rep(0, p)
  W_var = diag(p)
  W = rmvnorm(n = n, mean = W_mean, sigma = W_var)
  return(W)
}

get_true_treatment <- function(W,n){
  theta = rep(c(-1, 0.5, -0.25, -0.1),dim(W)[2]/4)
  pi = expit(W %*% theta)
  Z = rbernoulli(n = n, p = pi)
  return (Z)
}

get_true_outcome <- function(n,W,Z){
  ATE_true = 20
  beta = c(210, rep(c(27.4, 13.7, 13.7, 13.7),dim(W)[2]/4), ATE_true)
  eps = rnorm(n = n, mean = 0, sd = 1)
  y = cbind(rep(1, n), W, Z) %*% beta + eps
  return (y)
}

get_ATE_true_PS <- function(df_T){
  glm_t = glm(formula = Z ~ 0 + ., family = binomial(link = "logit"), data = df_T %>% select(-c(y)))

  pi_pred_W = predict(glm_t, type = "response")

  ATE_PS_norm_T = sum(df_T$Z*df_T$y/pi_pred_W)/sum(df_T$Z/pi_pred_W) - 
  sum((1 - df_T$Z)*df_T$y/(1 - pi_pred_W))/sum((1 - df_T$Z)/(1 - pi_pred_W))
  
  output=list()
  output[[1]] <- pi_pred_W
  output[[2]] <- ATE_PS_norm_T
  return(output)
}

get_PO_true_model <- function(df_T){
  lm_y = lm(formula = y ~ 1 + ., data = df_T)
  lm_y_summ = summary(lm_y)
  y_coef = lm_y_summ$coefficients
  
  dimension <- dim(df_T)
  dim1 <- dim(df_T)[1]
  dim2 <- dim(df_T)[2]
  
  y0_pred_W <- as.matrix(cbind(const=as.matrix(rep(1,dim1),ncol=1),df_T[,2:(dim2-1)])) %*% as.matrix(y_coef[1:(dim2-1)], ncol=1)
  
  y1_pred_W = y0_pred_W + y_coef[dim2]
  
  output=list()
  output[[1]] <- y0_pred_W
  output[[2]] <- y1_pred_W
  return(output)
  }

get_transformed_data <- function(W,y,Z){
  X=data.frame()
  for(i in seq(from=1,to=dim(W)[2],by=4)){
    X = rbind(X,exp(W[,i]/2))
    X = rbind(X,W[, (i+1)]/(1 + exp(W[,i])) + 10)
    X = rbind(X,(W[,i]*W[,(i+2)]*25 + 0.6)^3)
    X = rbind(X,(W[,(i+1)] + W[,(i+3)] + 20)^2)
  }

  X = t(X)
  rownames(X)<-NULL
  df_F = data.frame(y, X, Z)
  return(df_F)
}

get_ATE_PS_false <- function(df_F){
  glm_t_F = glm(formula = Z ~ 0 + ., family = binomial(link = "logit"), data = df_F %>% select(-c(y)))

  pi_pred_X = predict(glm_t_F, type = "response")
  ATE_PS_norm_F = sum(df_F$Z*df_F$y/pi_pred_X)/sum(df_F$Z/pi_pred_X) -
  sum((1 - df_F$Z)*df_F$y/(1 - pi_pred_X))/sum((1 - df_F$Z)/(1 - pi_pred_X))
  
  output=list()
  output[[1]] <- pi_pred_X
  output[[2]] <- ATE_PS_norm_F
  return(output)
  }

get_PO_false_model <- function(df_F){
  lm_y_F = lm(formula = y ~ 1 + ., data = df_F)
  lm_y_F_summ = summary(lm_y_F)
  y_coef_F = lm_y_F_summ$coefficients

  dimension <- dim(df_F)
  dim1 <- dim(df_F)[1]
  dim2 <- dim(df_F)[2]
  
  y0_pred_X <-   as.matrix(cbind(data.frame(const=as.matrix(rep(1,dim1),ncol=1)),df_F[2:(dim2-1)])) %*% as.matrix(y_coef_F[1:(dim2-1)], ncol=1)
  
  y1_pred_X = y0_pred_X + y_coef_F[dim2]
  
  output=list()
  output[[1]] <- y0_pred_X
  output[[2]] <- y1_pred_X
  return(output)
}

get_DR_estimates <- function(n,y1_pred_W,y1_pred_X,y0_pred_W,y0_pred_X,
                             pi_pred_W,pi_pred_X,df_T){
  ATE_double_TT = (1/n)*sum(y1_pred_W + df_T$Z*(df_T$y - y1_pred_W)/pi_pred_W) - 
  (1/n)*sum(y0_pred_W + (1 - df_T$Z)*(df_T$y - y0_pred_W)/(1 - pi_pred_W))
  
  ATE_double_TF = (1/n)*sum(y1_pred_W + df_T$Z*(df_T$y - y1_pred_W)/pi_pred_X) - 
  (1/n)*sum(y0_pred_W + (1 - df_T$Z)*(df_T$y - y0_pred_W)/(1 - pi_pred_X))
  
  ATE_double_FT = (1/n)*sum(y1_pred_X + df_T$Z*(df_T$y - y1_pred_X)/pi_pred_W) - 
  (1/n)*sum(y0_pred_X + (1 - df_T$Z)*(df_T$y - y0_pred_X)/(1 - pi_pred_W))
  
  ATE_double_FF = (1/n)*sum(y1_pred_X + df_T$Z*(df_T$y - y1_pred_X)/pi_pred_X) - 
  (1/n)*sum(y0_pred_X + (1 - df_T$Z)*(df_T$y - y0_pred_X)/(1 - pi_pred_X))
  
  output <- c(ATE_double_TT,ATE_double_TF,ATE_double_FT,ATE_double_FF)
  return(output)
}

get_DR_norm_estimates <- function(n,y1_pred_W,y1_pred_X,y0_pred_W,y0_pred_X,
                            pi_pred_W,pi_pred_X,df_T){
  ATE_double_TT = (mean(y1_pred_W) + sum(df_T$Z*(df_T$y - y1_pred_W)/pi_pred_W)/
                     sum(df_T$Z/pi_pred_W)) - 
    (mean(y0_pred_W) + sum((1 - df_T$Z)*(df_T$y - y0_pred_W)/(1 - pi_pred_W))/
       sum((1 - df_T$Z)/(1 - pi_pred_W)))

  ATE_double_TF = (mean(y1_pred_W) + sum(df_T$Z*(df_T$y - y1_pred_W)/pi_pred_X)/
                     sum(df_T$Z/pi_pred_X)) - 
    (mean(y0_pred_W) + sum((1 - df_T$Z)*(df_T$y - y0_pred_W)/(1 - pi_pred_X))/
       sum((1 - df_T$Z)/(1 - pi_pred_X)))

  ATE_double_FT = (mean(y1_pred_X) + sum(df_T$Z*(df_T$y - y1_pred_X)/pi_pred_W)/
                     sum(df_T$Z/pi_pred_W)) - 
    (mean(y0_pred_X) + sum((1 - df_T$Z)*(df_T$y - y0_pred_X)/(1 - pi_pred_W))/
       sum((1 - df_T$Z)/(1 - pi_pred_W)))
  
  ATE_double_FF = (mean(y1_pred_X) + sum(df_T$Z*(df_T$y - y1_pred_X)/pi_pred_X)/
                     sum(df_T$Z/pi_pred_X)) - 
    (mean(y0_pred_X) + sum((1 - df_T$Z)*(df_T$y - y0_pred_X)/(1 - pi_pred_X))/
       sum((1 - df_T$Z)/(1 - pi_pred_X)))
  
  output <- c(ATE_double_TT,ATE_double_TF,ATE_double_FT,ATE_double_FF)
  return(output)
}


```

```{r}
runSimulation <- function(W,n){
  #W_1 = W[,1]
  #W_2 = W[,2]
  #W_3 = W[,3]
  #W_4 = W[,4]
  
  Z <- get_true_treatment(W,n)
  y <- get_true_outcome(n,W,Z)
  
  df_T = data.frame(y, W, Z)
  
  output <- get_ATE_true_PS(df_T)
  pi_pred_W <- output[[1]]
  ATE_PS_norm_T <- output[[2]]
  
  output <- get_PO_true_model(df_T)
  y0_pred_W <- output[[1]]
  y1_pred_W <- output[[2]]
  ATE_outcome_T = (1/n)*sum(Z*(y - y0_pred_W) + (1 - Z)*(y1_pred_W - y))
  
  df_F <- get_transformed_data(W,y,Z)
  output <- get_ATE_PS_false(df_F)
  pi_pred_X <- output[[1]]
  ATE_PS_norm_F <- output[[2]]
  
  output <- get_PO_false_model(df_F)
  y0_pred_X <- output[[1]]
  y1_pred_X <- output[[2]]
  
  ATE_outcome_F = (1/n)*sum(Z*(y - y0_pred_X) + (1 - Z)*(y1_pred_X - y))
  
  # output <- get_DR_estimates(n,y1_pred_W,y1_pred_X,y0_pred_W,y0_pred_X,pi_pred_W,pi_pred_X,df_T)

  output <- get_DR_norm_estimates(n,y1_pred_W,y1_pred_X,y0_pred_W,y0_pred_X,pi_pred_W,pi_pred_X,df_T)
  
  ATE_double_TT <- output[1]
  ATE_double_TF <- output[2]
  ATE_double_FT <- output[3]
  ATE_double_FF <- output[4]
  
  output_row <- c(ATE_PS_norm_T,ATE_outcome_T,ATE_PS_norm_F, ATE_outcome_F, 
                         ATE_double_TT, ATE_double_TF,ATE_double_FT,ATE_double_FF)
  return(output_row)
}

```

```{r}
get_ate_with_se <- function(nSimulations,nBootstrap,n,p){
  outputSim <- data.frame(matrix(ncol = 8, nrow = nSimulations))
  colnames(outputSim) <- c("ATE_PS_norm_T","ATE_outcome_T",
                           "ATE_PS_norm_F", "ATE_outcome_F", 
                         "ATE_double_TT", "ATE_double_TF",
                         "ATE_double_FT","ATE_double_FF")

  se_sim <- outputSim

  for (i in 1:nSimulations){
    W <- generate_data(n,p)
    output_row <- runSimulation(W,n)
    outputSim[i,] <- output_row
    
    bootstrap_samples <- matrix(ncol=8, nrow=nBootstrap)
    for(j in 1:nBootstrap){
      bootstraped_index <- sample(1:nrow(W), replace = TRUE)
      bootstraped_data <- W[bootstraped_index,]
      bootstrap_samples[j,] <- runSimulation(bootstraped_data,n)
    }
    se_sim[i,] <- sqrt(apply(bootstrap_samples,2,var))
  }
  
  output <- list()
  output[[1]] <- outputSim
  output[[2]] <- se_sim
  return(output)
}

```


```{r, warning=FALSE}
nSimulations <- 100
nBootstrap <- 200

#100,300,500,1000,3000,5000
n_array <- c(100,300,500,1000,5000)
p_array <- c(8)

ate_df_p8 <- data.frame()
se_df_p8 <- data.frame()

for(j in 1:length(p_array)){
  print(c("doing j.. ",j))
  p <- p_array[j]
  for (i in 1:length(n_array)){
    print(c("doing i.. ",i))
    n <- n_array[i]
    output <- get_ate_with_se(nSimulations,nBootstrap,n,p)
    ate_df_p8 <- rbind(ate_df_p8,output[[1]] %>% mutate(n=n,p=p))
    se_df_p8 <- rbind(se_df_p8,output[[2]] %>% mutate(n=n,p=p))
  }
}  



ate_df %>% filter(p==4) %>% 
          group_by(n,p) %>% summarize(ATE_PS_norm_T=mean(ATE_PS_norm_T),
                                       ATE_outcome_T=mean(ATE_outcome_T),
                                       ATE_PS_norm_F=mean(ATE_PS_norm_F),
                                       ATE_outcome_F=mean(ATE_outcome_F),
                                       ATE_double_TT=mean(ATE_double_TT),
                                       ATE_double_TF=mean(ATE_double_TF),
                                       ATE_double_FT=mean(ATE_double_FT),
                                       ATE_double_FF=mean(ATE_double_FF)) %>% 
  melt(id=c("n","p"), variable.name="ATE") %>% 
  ggplot(aes(x=n,y=value,color=ATE)) +
  geom_line() + 
  labs(y="ATE", x="n: sample size")


se_df %>% filter(p==4) %>% 
          group_by(n,p) %>% summarize(ATE_PS_norm_T=mean(ATE_PS_norm_T),
                                       ATE_outcome_T=mean(ATE_outcome_T),
                                       ATE_PS_norm_F=mean(ATE_PS_norm_F),
                                       ATE_outcome_F=mean(ATE_outcome_F),
                                       ATE_double_TT=mean(ATE_double_TT),
                                       ATE_double_TF=mean(ATE_double_TF),
                                       ATE_double_FT=mean(ATE_double_FT),
                                       ATE_double_FF=mean(ATE_double_FF)) %>% 
  melt(id=c("n","p"), variable.name="ATE") %>% 
  ggplot(aes(x=n,y=value,color=ATE)) +
  geom_line() + 
  labs(y="SE", x="n: sample size")


# saving RData files
ate_df_p8 <- ate_df
se_df_p8 <- se_df

save(se_df_p4, file = "se_df_p4.RData")
save(ate_df_p4, file = "ate_df_p4.RData")

load(file = "se_df_p8.RData")
load(file = "ate_df_p8.RData")
```

```{r, warning=FALSE}
#graphs
bias <- cbind(ate_df %>% select(-c(n,p)) -20, ate_df %>% select(c(n,p)))
bias_div_se <- cbind((bias %>% select(-c(n,p)))/(se_df_p4 %>% select(-c(n,p))), bias %>% select(c(n,p)))

bias_div_se %>% filter(p==4) %>% 
          group_by(n,p) %>% summarize(ATE_PS_norm_T=mean(ATE_PS_norm_T),
                                       ATE_outcome_T=mean(ATE_outcome_T),
                                       ATE_PS_norm_F=mean(ATE_PS_norm_F),
                                       ATE_outcome_F=mean(ATE_outcome_F),
                                       ATE_double_TT=mean(ATE_double_TT),
                                       ATE_double_TF=mean(ATE_double_TF),
                                       ATE_double_FT=mean(ATE_double_FT),
                                       ATE_double_FF=mean(ATE_double_FF)) %>% 
  melt(id=c("n","p"), variable.name="ATE") %>% 
  ggplot(aes(x=n,y=value,color=ATE)) +
  geom_line() + 
  labs(y="ATE", x="n: sample size")
```

```{r, warning=FALSE}
#ate_df_p4 %>% filter(p==4) %>% select(-c(p)) %>% 
#  melt(id=c("n"), variable.name = "ATE") %>% 
#  ggplot(aes(x=value,y=..density..,fill=ATE))+
#  geom_density(alpha=0.3)+xlim(0,30)

p1 <- ate_df_p4 %>% select(c(ATE_PS_norm_T)) %>%   
  ggplot(aes(x=ATE_PS_norm_T,y=..density..))+
  geom_density(alpha=0.3,fill="blue")

p2 <- ate_df_p4 %>% select(c(ATE_outcome_T)) %>%   
  ggplot(aes(x=ATE_outcome_T,y=..density..))+
  geom_density(alpha=0.3,fill="blue")

p3 <- ate_df_p4 %>% select(c(ATE_PS_norm_F)) %>%   
  ggplot(aes(x=ATE_PS_norm_F,y=..density..))+
  geom_density(alpha=0.3,fill="blue")

p4 <- ate_df_p4 %>% select(c(ATE_outcome_F)) %>%   
  ggplot(aes(x=ATE_outcome_F,y=..density..))+
  geom_density(alpha=0.3,fill="blue")

p5 <- ate_df_p4 %>% select(c(ATE_double_TT)) %>%   
  ggplot(aes(x=ATE_double_TT,y=..density..))+
  geom_density(alpha=0.3,fill="blue")

p6 <- ate_df_p4 %>% select(c(ATE_double_TF)) %>%   
  ggplot(aes(x=ATE_double_TF,y=..density..))+
  geom_density(alpha=0.3,fill="blue")

p7 <- ate_df_p4 %>% select(c(ATE_double_FT)) %>%   
  ggplot(aes(x=ATE_double_FT,y=..density..))+
  geom_density(alpha=0.3,fill="blue")

p8 <- ate_df_p4 %>% select(c(ATE_double_FF)) %>%   
  ggplot(aes(x=ATE_double_FF,y=..density..))+
  geom_density(alpha=0.3,fill="blue")

grid.arrange(p1, p2, p3, p4, p5, p6, p7, p8, nrow=3)
```



